Numpy : Practice Problem

Extract all odd numbers from arr:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Replace all odd numbers in arr with -1

In [6]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [7]:
import numpy as np


## Extract all odd numbers from arr: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) 

In [129]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2 == 1]  


array([1, 3, 5, 7, 9])

## Replace all odd numbers in arr with -1

In [122]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2 != 0] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## Convert a 1D array to a 2D array with 2 rows

In [10]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.reshape(arr,(2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Stack arrays a and b vertically



In [17]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [19]:
print("Vertical array: ",'\n',np.vstack((a,b)))

Vertical array:  
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## Get all items between 5 and 10 from a



In [88]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a>5)&(a<10)]


array([6, 9])

## Create a null vector of size 10 but the fifth value which is 1.

In [37]:
vector = np.zeros(10)
vector[4] = 1
vector


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

## Create a vector with values ranging from 10 to 49.

In [39]:
vector = np.arange(10,49)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

## Create a 10x10 array with random values and find the minimum and maximum values.

In [50]:
arr = np.random.rand(10,10)
arr

array([[0.49042941, 0.66859099, 0.2407256 , 0.89113342, 0.87018887,
        0.97868213, 0.93462504, 0.83736822, 0.28640547, 0.05529284],
       [0.38473227, 0.2868259 , 0.34984301, 0.08630478, 0.98110038,
        0.71949064, 0.00945695, 0.30168228, 0.07879934, 0.52025002],
       [0.6234323 , 0.40844631, 0.55646126, 0.50432504, 0.17719572,
        0.39352073, 0.7191022 , 0.97572121, 0.36135807, 0.12404682],
       [0.26024854, 0.57703877, 0.82452444, 0.24065165, 0.41316253,
        0.98056127, 0.29624844, 0.03000214, 0.62655913, 0.32597807],
       [0.26797713, 0.19403665, 0.03561921, 0.80735853, 0.82667636,
        0.76437234, 0.67351037, 0.18965774, 0.72579986, 0.32345399],
       [0.0624649 , 0.55025011, 0.34482787, 0.58920644, 0.33480376,
        0.59035692, 0.51922437, 0.70232275, 0.032665  , 0.06080439],
       [0.23701153, 0.0864229 , 0.62760398, 0.55410342, 0.05005072,
        0.96804974, 0.78510868, 0.90208959, 0.51567612, 0.18380433],
       [0.67221069, 0.09437577, 0.6269891

In [56]:
arr.min()

0.00945695461716789

In [57]:
arr.max()

0.9811003842734914

## Create a 3*3 matrix and print it's transpose matrix

In [69]:
matrix = np.arange(1,10).reshape(3,3)
matrix


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
np.transpose(matrix)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## Create two arrays of 2-D and find dot product of it.

In [73]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])

In [74]:
a*b

array([[ 5, 12],
       [21, 32]])

In [75]:
a.dot(b)

array([[19, 22],
       [43, 50]])

## Compute the maximum for each row in the given array.

In [116]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a

array([[9, 9, 4],
       [8, 8, 1],
       [5, 3, 6],
       [3, 3, 3],
       [2, 1, 9]])

In [117]:
a = np.amax(a,axis = 1)
print(a)

[9 8 6 3 9]


## Convert below matrix into vector



In [79]:
matrix = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])

In [81]:
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## The product of two inverse matrix is identical matrix,prove

# create a square matrix


In [83]:
m = np.array([[2,3],
              [2,4]])

In [89]:
np.linalg.inv(m)

array([[ 2. , -1.5],
       [-1. ,  1. ]])

## Create a matrix from a uniform distribution over [0, 1)

In [101]:
data = np.random.uniform(0,1,(3,3))

In [102]:
data

array([[0.00581719, 0.30742321, 0.95018431],
       [0.12665424, 0.07898787, 0.31135313],
       [0.63238359, 0.69935892, 0.64196495]])

## Select 3rd & 5th row and 3rd & 4th columns



In [132]:
data = np.random.randint(10,100,(5,4))
data

array([[25, 70, 68, 26],
       [19, 96, 12, 37],
       [14, 41, 11, 23],
       [93, 14, 69, 77],
       [17, 59, 57, 75]])

In [140]:
data[[2,4],2:4]

array([[11, 23],
       [57, 75]])